# Roteiro

#### Gnucash
- [x] Acessar arquivo do gnucash
- [x] Ler t ransações
- [ ] Comparar transações entre ofx e gnucash
- [ ] Escrever transação no gnucash
- [ ] Escrever transação split no gnucash

#### XML e ofx
- [x] Escolher pacote de leitura de xml
- [x] Ler arquivo ofx
- [x] Ler os campos necessários
- [x] Otimizar performance

### Sqlachemy
- [x] Atualizar o código de controle de arquivo
- [x] Construir o código de Ofx
- [x] Criar os relacionamentos
- [x] Fazer validação dos dados no banco sqlite


### classificações
- [ ] Criar casca para classificação
- [ ] Ler classificações do excel
- [ ] Contruir de-para entre classificação do excel e do gnucash
- [ ] Encontrar classificação mais próxima por similaridade

In [15]:
# !pip install piecash
# !pip install rarfile
# !pip install pandas

Requirement already satisfied: piecash in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (1.2.0)
Requirement already satisfied: SQLAlchemy<1.4,>=1.0 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from piecash) (1.3.24)
Requirement already satisfied: SQLAlchemy-Utils!=0.36.8 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from piecash) (0.41.2)
Requirement already satisfied: pytz in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from piecash) (2024.1)
Requirement already satisfied: tzlocal in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from piecash) (5.2)
Requirement already satisfied: click in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from piecash) (8.1.7)
Requirement already satisfied: colorama in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from click->piecash) (0.4.6)
Requirement already satisfied: tzdata in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from tzlocal->piecash) (2024.1)
Requirement already satisfied: rarfile in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (4.2)
Requirement already satisfied: pandas in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\cfreitas\anaconda3\envs\env_39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

ERROR: Could not find a version that satisfies the requirement models.ofx (from versions: none)
ERROR: No matching distribution found for models.ofx

In [12]:
# Exemplos https://piecash.readthedocs.io/en/master/tutorial/examples.html

import os
from decimal import Decimal
from piecash import open_book, create_book, GnucashException
from piecash import create_book, Account, Transaction, Split, Commodity
from piecash.core.factories import create_currency_from_ISO

import pandas as pd
import datetime as dt

In [2]:
import piecash
dir(piecash)

['ACCOUNT_TYPES',
 'Account',
 'AccountType',
 'Address',
 'Book',
 'Budget',
 'BudgetAmount',
 'Commodity',
 'Customer',
 'Employee',
 'GncImbalanceError',
 'GncNoActiveSession',
 'GncValidationError',
 'GnucashException',
 'Invoice',
 'Job',
 'Lot',
 'Price',
 'Recurrence',
 'ScheduledTransaction',
 'Split',
 'Taxtable',
 'TaxtableEntry',
 'Transaction',
 'Vendor',
 '__author__',
 '__builtins__',
 '__cached__',
 '__copyright__',
 '__doc__',
 '__file__',
 '__license__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_common',
 '_declbase',
 'budget',
 'business',
 'core',
 'create_book',
 'factories',
 'kvp',
 'ledger',
 'metadata',
 'open_book',
 'sa_extra',
 'slot',
 'yahoo_client']

In [8]:
# D:\Users\cfreitas\OneDrive\Code\Contabilidade\teste_gnucash_4
pasta_gnucash = "./"
arquivo_gnucash = "sqlite3_2024-05-08.gnucash"
#"pessoal_2021-08-02.gnucash"
#"teste_gnucash_4_sqlite_3.gnucash"
path_gnucash = os.path.join(pasta_gnucash, arquivo_gnucash)

# Abre o banco do gnucash em sqlite com open_book
with open_book(path_gnucash) as mybook:
    # get default currency of book
    print( mybook.default_currency )  # ==> Commodity<CURRENCY:EUR>

    # iterating over all splits in all books and print the transaction description:
    for acc in mybook.accounts:
        for sp in acc.splits:
            print(sp.transaction)

Commodity<CURRENCY:BRL>
Transaction<[BRL] 'teste de transação (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'terceiro teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'quarto teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'teste de transação (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'terceiro teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'quarto teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-01>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-01>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-01>
Transaction<[BRL] 'segundo teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'segundo teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'terceiro teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'terceiro teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'teste de transação (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'segundo teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'terceiro teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'quarto teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'teste de transação (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'segundo teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'terceiro teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'quarto teste (some extra info added to the description)' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-08>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-01>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-01>
Transaction<[BRL] 'Transacao criada fora 1' on 2024-05-01>

In [13]:
from piecash import open_book, ledger, Split

with open_book(
    arquivo_gnucash, readonly=True, open_if_lock=True
) as mybook:
    for transaction in mybook.transactions:
        print(transaction.__dict__)
        print('description:' + transaction.description)

    # print(ledger(mybook))

df = mybook.splits_df()
df

{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7775F40>, 'guid': 'ec9080da6da5480b9c163b32cbb910c3', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 15, 7, 31, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '111', 'description': 'teste de transação (some extra info added to the description)'}
description:teste de transação (some extra info added to the description)
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7775E90>, 'guid': '7a938f0aa6004a6b960b0261bcdc07c4', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 15, 8, 15, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '222', 'description': 'segundo teste (some extra info added to the description)'}
description:segundo teste (some extra info added to the description)
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7775DE0>, 'guid': 'b838d1a67e154a08b3cc4b89de0262e4', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 15, 31, 1, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '333', 'description': 'terceiro teste (some extra info added to the description)'}
description:terceiro teste (some extra info added to the description)
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B77762B0>, 'guid': '6b2b9be07f4142d9b36da68780a7ac9a', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 15, 45, 38, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '444', 'description': 'quarto teste (some extra info added to the description)'}
description:quarto teste (some extra info added to the description)
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776360>, 'guid': '51ecdb1377bc4cd499a79e97a3c03164', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 16, 7, 12, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776410>, 'guid': 'ffebaec04ba44319a13d1902f9139b29', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 16, 7, 13, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B77764C0>, 'guid': '4943ff33acf6423fbae3b40e46195cad', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 8, 16, 7, 14, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776570>, 'guid': 'd08cd8866979460eb00ccad77caa4f81', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776620>, 'guid': '52cd32fa4ba846598c811515dfb52896', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B77766D0>, 'guid': '352951f035dc42da85709542022e89e9', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776780>, 'guid': 'cfabe56bb68548b7bb88186ea3ec593a', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776830>, 'guid': '8021c7856f18441e8e8f76e75bcfb9e3', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 8), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B77768E0>, 'guid': '8859daff1164477d9a490a3644b982d3', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 1), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776990>, 'guid': '3540f8c88a28425197b678b1a0497e25', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 1), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001F3B7776A40>, 'guid': 'b7ae2945b83b499c8c5838284e0d4287', 'currency_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'enter_date': datetime.datetime(2024, 5, 1, 0, 0, tzinfo=<DstTzInfo 'America/Sao_Paulo' -03-1 day, 21:00:00 STD>), '_post_date': datetime.date(2024, 5, 1), 'num': '1.1', 'description': 'Transacao criada fora 1'}
description:Transacao criada fora 1

D:\OneDrive\Aprendizado\Concurso\python\processa_pdf\.venv\Lib\site-packages\piecash\core\book.py:547: SAWarning: TypeDecorator _DateAsDateTime() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  .all()

,value,quantity,memo,transaction.guid,transaction.description,transaction.post_date,transaction.currency.guid,transaction.currency.mnemonic,account.fullname,account.commodity.guid,account.commodity.mnemonic
guid,,,,,,,,,,,
683d35c83ac947628add6514aa53d7f9,-100,-100,,8859daff1164477d9a490a3644b982d3,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
57393466352541359a82ea515a3a28fd,-100,-100,,3540f8c88a28425197b678b1a0497e25,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a9b7ef281d8a4e4abc3b003049efc3bf,-100,-100,,b7ae2945b83b499c8c5838284e0d4287,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c8d35d348bb842b78b98e2b22131ee80,100,100,,8859daff1164477d9a490a3644b982d3,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
028b981370e541d4b670afaa438b5c00,100,100,,3540f8c88a28425197b678b1a0497e25,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
8f98d0c8763d4d9fa5ade0858c1e1035,100,100,,b7ae2945b83b499c8c5838284e0d4287,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
340d0eef17f64cd7a403a94268e8c2ba,-800,-800,,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
9fb4abfc80e64a02990ea5b336569684,-400,-400,split numero 3,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3ffea02137c848809c72ff8a7df8d31e,-300,-300,split numero 2,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Dinheiro na Carteira,de9498f01a7d43fa8e0e3d1d06752a13,BRL
d54b1d7b2e4641b4b687bd090acf8ead,-200,-200,,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Poupança,de9498f01a7d43fa8e0e3d1d06752a13,BRL
4bae5c736ad141ddbd0d48c3cf1367bb,-100,-100,,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
b5abafdeed4b4d57877e520d5d76126e,-100,-100,,51ecdb1377bc4cd499a79e97a3c03164,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
ab192b92f540440db87e968153299bbb,-100,-100,,ffebaec04ba44319a13d1902f9139b29,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
b076d00036354a52adc7d761332fa9dd,-100,-100,,4943ff33acf6423fbae3b40e46195cad,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
1122bb4b7a53470e828ceb62bf4586cc,-100,-100,,d08cd8866979460eb00ccad77caa4f81,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
6ff9441a83834d6d83cfffcae9ec5a28,-100,-100,,52cd32fa4ba846598c811515dfb52896,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
d1c4beeba54740e38e66c2ee258b9299,-100,-100,,352951f035dc42da85709542022e89e9,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
2a13d192a2fa45d6a7ab906741e4f9d5,-100,-100,,cfabe56bb68548b7bb88186ea3ec593a,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
bba184750eab460588cc4bf001a0c0b8,-100,-100,,8021c7856f18441e8e8f76e75bcfb9e3,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a37a84bc92ae4c329aefd58fdec6404b,-80,-80,my new split,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c1a909524923404f982598e0288d7d21,-40,-40,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
922f2b2b2bc646f28542a1595684f7a3,-30,-30,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Dinheiro na Carteira,de9498f01a7d43fa8e0e3d1d06752a13,BRL
aed182f3b04f471ababbff5355182411,-20,-20,my new split,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Poupança,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c415bfc9ef184414a7915d25823766d6,-10,-10,my new split,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
0f172f2b109445bba5c0ccc11e18832b,10,10,my new split,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a3a467b0be8b4d3fbd80cc1785eaab67,20,20,my new split,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
25b8de021e2d4d60a7ac21b837e51263,70,70,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
9d245ac533564329b88309876388ad96,80,80,my new split,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3aa7584ec55b4c09bf061005e18d96a3,100,100,,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
365213fdc76d4d4e9957bc3bb43aa7d1,100,100,,51ecdb1377bc4cd499a79e97a3c03164,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
343c9fc516a24a3f85af85679f31e368,100,100,,ffebaec04ba44319a13d1902f9139b29,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
e5e777f679d54a32b28f57314f965d45,100,100,,4943ff33acf6423fbae3b40e46195cad,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a472f8304aa84ac9b421dd3e7a8fda29,100,100,,d08cd8866979460eb00ccad77caa4f81,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
ec7f87423f424a149cc095066a336440,100,100,,52cd32fa4ba846598c811515dfb52896,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
02746951f4c24fb7a7d049f162d540f0,100,100,,352951f035dc42da85709542022e89e9,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
6c2dd31e23634d1ca491da3145c98996,100,100,,cfabe56bb68548b7bb88186ea3ec593a,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c8f109e729d64a4da4bdd64bad66d6d6,100,100,,8021c7856f18441e8e8f76e75bcfb9e3,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
14b69f39fb6c454cac200f56f11bc15b,200,200,,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3cf45963651244d194b98711b8216990,700,700,split numero 1,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
4e91d4e7fe4746a1bd7a19d68fdd0df3,800,800,,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL

In [14]:
dir(Transaction)

['__abstract__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__mapper__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__table__',
 '__table_args__',
 '__tablename__',
 '__weakref__',
 '_post_date',
 '_sa_class_manager',
 '_sa_registry',
 'book',
 'calculate_imbalances',
 'currency',
 'currency_guid',
 'description',
 'enter_date',
 'get',
 'get_all_changes',
 'guid',
 'iteritems',
 'metadata',
 'normalize_trading_accounts',
 'notes',
 'num',
 'object_to_validate',
 'on_book_add',
 'post_date',
 'registry',
 'scheduled_transaction',
 'slots',
 'splits',
 'validate']

In [15]:
from datetime import datetime,date

datetime(2024,1,1)

datetime.datetime(2024, 1, 1, 0, 0)

In [17]:
from piecash import create_book, Account, Transaction, Split, GncImbalanceError, factories, ledger

with open_book(
    arquivo_gnucash, readonly=False, open_if_lock=True
) as mybook:
    conta1 = mybook.accounts(fullname="Despesas:Doações")
    conta2 = mybook.accounts(fullname="Ativos:Ativos Atuais:Conta Corrente")
    
    transacao = Transaction(
        currency=mybook.default_currency,
        description = 'Transacao criada fora 1',
        splits=[
            Split(account=conta1, value=-100), # 
            Split(account=conta2, value=100),     
        ],
        enter_date=dt.datetime(2024,5,1),
# 'notes',
        num = '1.1',
        post_date = date(2024,5,1),
 # 'scheduled_transaction',
 # 'slots',
 # 'splits',
 # 'validate'
    )

    mybook.flush()
    mybook.save()
    
    df = mybook.splits_df()

    print(transacao.slots)
    
# df

[<SlotDate date-posted=datetime.date(2024, 5, 1)>]

In [18]:
df

,value,quantity,memo,transaction.guid,transaction.description,transaction.post_date,transaction.currency.guid,transaction.currency.mnemonic,account.fullname,account.commodity.guid,account.commodity.mnemonic
guid,,,,,,,,,,,
683d35c83ac947628add6514aa53d7f9,-100,-100,,8859daff1164477d9a490a3644b982d3,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
57393466352541359a82ea515a3a28fd,-100,-100,,3540f8c88a28425197b678b1a0497e25,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a9b7ef281d8a4e4abc3b003049efc3bf,-100,-100,,b7ae2945b83b499c8c5838284e0d4287,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
8e05c2409553453e9e3579c256d216cb,-100,-100,,f60a1cfcfd2c425eb451b9bb8746097c,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
1622b6c8f67a4db39825e045b7bbb976,-100,-100,,303e416d350742f58eb03c63d512c5df,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c8d35d348bb842b78b98e2b22131ee80,100,100,,8859daff1164477d9a490a3644b982d3,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
028b981370e541d4b670afaa438b5c00,100,100,,3540f8c88a28425197b678b1a0497e25,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
8f98d0c8763d4d9fa5ade0858c1e1035,100,100,,b7ae2945b83b499c8c5838284e0d4287,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c338789524f842d982cd31e5e3c1ae94,100,100,,f60a1cfcfd2c425eb451b9bb8746097c,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
1e2c324a6138468d9186865962639e00,100,100,,303e416d350742f58eb03c63d512c5df,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
340d0eef17f64cd7a403a94268e8c2ba,-800,-800,,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
9fb4abfc80e64a02990ea5b336569684,-400,-400,split numero 3,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3ffea02137c848809c72ff8a7df8d31e,-300,-300,split numero 2,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Dinheiro na Carteira,de9498f01a7d43fa8e0e3d1d06752a13,BRL
d54b1d7b2e4641b4b687bd090acf8ead,-200,-200,,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Poupança,de9498f01a7d43fa8e0e3d1d06752a13,BRL
4bae5c736ad141ddbd0d48c3cf1367bb,-100,-100,,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
b5abafdeed4b4d57877e520d5d76126e,-100,-100,,51ecdb1377bc4cd499a79e97a3c03164,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
ab192b92f540440db87e968153299bbb,-100,-100,,ffebaec04ba44319a13d1902f9139b29,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
b076d00036354a52adc7d761332fa9dd,-100,-100,,4943ff33acf6423fbae3b40e46195cad,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
1122bb4b7a53470e828ceb62bf4586cc,-100,-100,,d08cd8866979460eb00ccad77caa4f81,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
6ff9441a83834d6d83cfffcae9ec5a28,-100,-100,,52cd32fa4ba846598c811515dfb52896,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
d1c4beeba54740e38e66c2ee258b9299,-100,-100,,352951f035dc42da85709542022e89e9,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
2a13d192a2fa45d6a7ab906741e4f9d5,-100,-100,,cfabe56bb68548b7bb88186ea3ec593a,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
bba184750eab460588cc4bf001a0c0b8,-100,-100,,8021c7856f18441e8e8f76e75bcfb9e3,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a37a84bc92ae4c329aefd58fdec6404b,-80,-80,my new split,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c1a909524923404f982598e0288d7d21,-40,-40,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
922f2b2b2bc646f28542a1595684f7a3,-30,-30,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Dinheiro na Carteira,de9498f01a7d43fa8e0e3d1d06752a13,BRL
aed182f3b04f471ababbff5355182411,-20,-20,my new split,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Poupança,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c415bfc9ef184414a7915d25823766d6,-10,-10,my new split,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
0f172f2b109445bba5c0ccc11e18832b,10,10,my new split,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a3a467b0be8b4d3fbd80cc1785eaab67,20,20,my new split,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
25b8de021e2d4d60a7ac21b837e51263,70,70,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
9d245ac533564329b88309876388ad96,80,80,my new split,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3aa7584ec55b4c09bf061005e18d96a3,100,100,,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
365213fdc76d4d4e9957bc3bb43aa7d1,100,100,,51ecdb1377bc4cd499a79e97a3c03164,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
343c9fc516a24a3f85af85679f31e368,100,100,,ffebaec04ba44319a13d1902f9139b29,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
e5e777f679d54a32b28f57314f965d45,100,100,,4943ff33acf6423fbae3b40e46195cad,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a472f8304aa84ac9b421dd3e7a8fda29,100,100,,d08cd8866979460eb00ccad77caa4f81,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
ec7f87423f424a149cc095066a336440,100,100,,52cd32fa4ba846598c811515dfb52896,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
02746951f4c24fb7a7d049f162d540f0,100,100,,352951f035dc42da85709542022e89e9,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
6c2dd31e23634d1ca491da3145c98996,100,100,,cfabe56bb68548b7bb88186ea3ec593a,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c8f109e729d64a4da4bdd64bad66d6d6,100,100,,8021c7856f18441e8e8f76e75bcfb9e3,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
14b69f39fb6c454cac200f56f11bc15b,200,200,,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3cf45963651244d194b98711b8216990,700,700,split numero 1,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
4e91d4e7fe4746a1bd7a19d68fdd0df3,800,800,,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL

In [19]:
transacao.slots

DetachedInstanceError: Parent instance <Transaction at 0x1f3b785d650> is not bound to a Session; lazy load operation of attribute 'slots' cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)

In [21]:
from piecash import open_book, ledger, Split

with open_book(
    arquivo_gnucash, readonly=True, open_if_lock=True
) as mybook:
    df = mybook.splits_df()
    
df.sort_values(by=['transaction.post_date','transaction.guid'])

# transaction.guid	
# transaction.description	
# transaction.post_date

# transaction.currency.guid	transaction.currency.mnemonic

# guid
# value
# quantity
# account.fullname
# memo

D:\OneDrive\Aprendizado\Concurso\python\processa_pdf\.venv\Lib\site-packages\piecash\core\book.py:547: SAWarning: TypeDecorator _DateAsDateTime() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  .all()

,value,quantity,memo,transaction.guid,transaction.description,transaction.post_date,transaction.currency.guid,transaction.currency.mnemonic,account.fullname,account.commodity.guid,account.commodity.mnemonic
guid,,,,,,,,,,,
1622b6c8f67a4db39825e045b7bbb976,-100,-100,,303e416d350742f58eb03c63d512c5df,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
1e2c324a6138468d9186865962639e00,100,100,,303e416d350742f58eb03c63d512c5df,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
57393466352541359a82ea515a3a28fd,-100,-100,,3540f8c88a28425197b678b1a0497e25,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
028b981370e541d4b670afaa438b5c00,100,100,,3540f8c88a28425197b678b1a0497e25,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
683d35c83ac947628add6514aa53d7f9,-100,-100,,8859daff1164477d9a490a3644b982d3,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c8d35d348bb842b78b98e2b22131ee80,100,100,,8859daff1164477d9a490a3644b982d3,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a9b7ef281d8a4e4abc3b003049efc3bf,-100,-100,,b7ae2945b83b499c8c5838284e0d4287,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
8f98d0c8763d4d9fa5ade0858c1e1035,100,100,,b7ae2945b83b499c8c5838284e0d4287,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
8e05c2409553453e9e3579c256d216cb,-100,-100,,f60a1cfcfd2c425eb451b9bb8746097c,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c338789524f842d982cd31e5e3c1ae94,100,100,,f60a1cfcfd2c425eb451b9bb8746097c,Transacao criada fora 1,2024-05-01,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
d1c4beeba54740e38e66c2ee258b9299,-100,-100,,352951f035dc42da85709542022e89e9,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
02746951f4c24fb7a7d049f162d540f0,100,100,,352951f035dc42da85709542022e89e9,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
b076d00036354a52adc7d761332fa9dd,-100,-100,,4943ff33acf6423fbae3b40e46195cad,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
e5e777f679d54a32b28f57314f965d45,100,100,,4943ff33acf6423fbae3b40e46195cad,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
b5abafdeed4b4d57877e520d5d76126e,-100,-100,,51ecdb1377bc4cd499a79e97a3c03164,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
365213fdc76d4d4e9957bc3bb43aa7d1,100,100,,51ecdb1377bc4cd499a79e97a3c03164,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
6ff9441a83834d6d83cfffcae9ec5a28,-100,-100,,52cd32fa4ba846598c811515dfb52896,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
ec7f87423f424a149cc095066a336440,100,100,,52cd32fa4ba846598c811515dfb52896,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
340d0eef17f64cd7a403a94268e8c2ba,-800,-800,,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a37a84bc92ae4c329aefd58fdec6404b,-80,-80,my new split,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
9d245ac533564329b88309876388ad96,80,80,my new split,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
4e91d4e7fe4746a1bd7a19d68fdd0df3,800,800,,6b2b9be07f4142d9b36da68780a7ac9a,quarto teste (some extra info added to the des...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
d54b1d7b2e4641b4b687bd090acf8ead,-200,-200,,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Poupança,de9498f01a7d43fa8e0e3d1d06752a13,BRL
aed182f3b04f471ababbff5355182411,-20,-20,my new split,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Poupança,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a3a467b0be8b4d3fbd80cc1785eaab67,20,20,my new split,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
14b69f39fb6c454cac200f56f11bc15b,200,200,,7a938f0aa6004a6b960b0261bcdc07c4,segundo teste (some extra info added to the de...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
bba184750eab460588cc4bf001a0c0b8,-100,-100,,8021c7856f18441e8e8f76e75bcfb9e3,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c8f109e729d64a4da4bdd64bad66d6d6,100,100,,8021c7856f18441e8e8f76e75bcfb9e3,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
9fb4abfc80e64a02990ea5b336569684,-400,-400,split numero 3,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3ffea02137c848809c72ff8a7df8d31e,-300,-300,split numero 2,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Dinheiro na Carteira,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c1a909524923404f982598e0288d7d21,-40,-40,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
922f2b2b2bc646f28542a1595684f7a3,-30,-30,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Dinheiro na Carteira,de9498f01a7d43fa8e0e3d1d06752a13,BRL
25b8de021e2d4d60a7ac21b837e51263,70,70,my new split,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3cf45963651244d194b98711b8216990,700,700,split numero 1,b838d1a67e154a08b3cc4b89de0262e4,terceiro teste (some extra info added to the d...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
2a13d192a2fa45d6a7ab906741e4f9d5,-100,-100,,cfabe56bb68548b7bb88186ea3ec593a,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
6c2dd31e23634d1ca491da3145c98996,100,100,,cfabe56bb68548b7bb88186ea3ec593a,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
1122bb4b7a53470e828ceb62bf4586cc,-100,-100,,d08cd8866979460eb00ccad77caa4f81,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
a472f8304aa84ac9b421dd3e7a8fda29,100,100,,d08cd8866979460eb00ccad77caa4f81,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
4bae5c736ad141ddbd0d48c3cf1367bb,-100,-100,,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
c415bfc9ef184414a7915d25823766d6,-10,-10,my new split,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL
0f172f2b109445bba5c0ccc11e18832b,10,10,my new split,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
3aa7584ec55b4c09bf061005e18d96a3,100,100,,ec9080da6da5480b9c163b32cbb910c3,teste de transação (some extra info added to t...,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
ab192b92f540440db87e968153299bbb,-100,-100,,ffebaec04ba44319a13d1902f9139b29,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Despesas:Doações,de9498f01a7d43fa8e0e3d1d06752a13,BRL
343c9fc516a24a3f85af85679f31e368,100,100,,ffebaec04ba44319a13d1902f9139b29,Transacao criada fora 1,2024-05-08,de9498f01a7d43fa8e0e3d1d06752a13,BRL,Ativos:Ativos Atuais:Conta Corrente,de9498f01a7d43fa8e0e3d1d06752a13,BRL

In [23]:
df.columns

Index(['value', 'quantity', 'memo', 'transaction.guid',
       'transaction.description', 'transaction.post_date',
       'transaction.currency.guid', 'transaction.currency.mnemonic',
       'account.fullname', 'account.commodity.guid',
       'account.commodity.mnemonic'],
      dtype='object')

In [54]:
mybook.close()

In [56]:
dir(mybook)

['RO_threshold_day',
 '__abstract__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__mapper__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__table__',
 '__table_args__',
 '__tablename__',
 '__weakref__',
 '_control_mode',
 '_decl_class_registry',
 '_sa_class_manager',
 '_sa_instance_state',
 '_trading_accounts',
 'accounts',
 'add',
 'book',
 'business_company_ID',
 'business_company_address',
 'business_company_contact',
 'business_company_email',
 'business_company_name',
 'business_company_phone',
 'business_company_website',
 'cancel',
 'close',
 'commodities',
 'control_mode',
 'counter_bill',
 'counter_customer',
 'counter_employee',
 'counter_exp_voucher',
 'counter_invoice',
 'counter_job',
 'counter_order',
 'counter_vendor',
 'currencies',
 'customers',
 'default_currency',
 'delete',
 'employees',
 'flush',
 'get',
 'get_all_changes',
 'guid',
 'invoices',
 'is_saved',
 'iteritems',
 'metadata',
 'object_to_validate',
 'on_book_add',
 'preload',
 'prices',
 'prices_df',
 'query',
 'root_account',
 'root_account_guid',
 'root_template',
 'root_template_guid',
 'save',
 'session',
 'session_changes',
 'slots',
 'splits',
 'splits_df',
 'taxtables',
 'track_dirty',
 'trading_account',
 'transactions',
 'uri',
 'use_split_action_field',
 'use_trading_accounts',
 'validate',
 'validate_book',
 'vendors']

In [64]:
dir(piecash)

NameError: name 'piecash' is not defined

In [61]:
with open_book(
    arquivo_gnucash, readonly=False#readonly=True, open_if_lock=True
) as mybook:
    for acc in mybook.root_account.children:
        print(acc)
        for acc2 in acc.children:
            print(acc2)

Account<Ativos[BRL]>
Account<Ativos:Ativos Atuais[BRL]>
Account<Passivo[BRL]>
Account<Passivo:Contas a Pagar[BRL]>
Account<Passivo:Cartão de Crédito[BRL]>
Account<Receitas[BRL]>
Account<Receitas:Bônus[BRL]>
Account<Receitas:Presentes Recebidos[BRL]>
Account<Receitas:Juros Recebidos[BRL]>
Account<Receitas:Outras Receitas[BRL]>
Account<Receitas:Salário[BRL]>
Account<Despesas[BRL]>
Account<Despesas:Ajustes[BRL]>
Account<Despesas:Transporte[BRL]>
Account<Despesas:Taxas Bancárias[BRL]>
Account<Despesas:Livros[BRL]>
Account<Despesas:Doações[BRL]>
Account<Despesas:Vestuário[BRL]>
Account<Despesas:Refeições Fora[BRL]>
Account<Despesas:Educação[BRL]>
Account<Despesas:Diversão[BRL]>
Account<Despesas:Presentes[BRL]>
Account<Despesas:Saúde[BRL]>
Account<Despesas:Outras[BRL]>
Account<Despesas:Serviços[BRL]>
Account<Despesas:Mercado[BRL]>
Account<Líquido[BRL]>
Account<Líquido:Saldos Iniciais[BRL]>

In [58]:
with open_book(
    arquivo_gnucash, readonly=False#readonly=True, open_if_lock=True
) as mybook:
    # iterate on all the transactions in the book
    for transaction in mybook.transactions:
        # add some extra text to the transaction description
        transaction.description = (
            transaction.description + " (some extra info added to the description)"
        )
        # iterate over all the splits of the transaction
        # as we will modify the transaction splits in the loop,
        # we need to use list(...) to take a copy of the splits at the start of the loop
        for split in list(transaction.splits):
            # create the new split (here a copy of the each existing split
            # in the transaction with value/quantity divided by 10)
            new_split = Split(
                account=split.account,
                value=split.value / 10,
                quantity=split.quantity / 10,
                memo="my new split",
                transaction=transaction,  # attach the split to the current transaction
            )
    # register the changes (but not save)
    mybook.flush()

    # print the book in ledger format to view the changes
    # print(ledger(mybook))

    # save the book
    # this will raise an error as readonly=True (change to readonly=False to successfully save the book)
    mybook.save()

In [16]:
# Busca informação das contas
df = pd.DataFrame()
lista_contas = []
for i in (mybook.accounts):
    #print(i.name + ' | ' + i.type + ' | ' +  str(i.placeholder) + ' | ' + i.code)
    # df = df.append({'code':i.code,'name':i.name,'type':i.type,'placeholder':str(i.placeholder),'description':i.description}, ignore_index=True)
    lista_contas.append(i.__dict__)
    # print(i.__dict__)
    
# df[df["type"] == "ASSET"]
# df

df = pd.DataFrame(lista_contas)

In [17]:
mybook

Book<sqlite:///./sqlite3_2024-05-08.gnucash>

In [13]:
for account in mybook.accounts:
    print(account.__dict__)

{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D2E0>, 'name': 'Ativos', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '8f14959583c94e0683565b020757a7e0', 'code': '', 'type': 'ASSET', 'description': 'Ativos', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '707ac8f3ed36400bb972aa487705404b'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D400>, 'name': 'Ativos Atuais', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '707ac8f3ed36400bb972aa487705404b', 'code': '', 'type': 'ASSET', 'description': 'Ativos Atuais', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'b71f1c7eb1f142d9ae5e4d67959e1546'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D4C0>, 'name': 'Conta Corrente', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'b71f1c7eb1f142d9ae5e4d67959e1546', 'code': '', 'type': 'BANK', 'description': 'Conta Corrente', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'cc831897ca8b4392b17451c1126e5a2e'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D580>, 'name': 'Conta Poupança', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'b71f1c7eb1f142d9ae5e4d67959e1546', 'code': '', 'type': 'BANK', 'description': 'Conta Poupança', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'ec3c2591d0984dd29589109f8f857f45'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D640>, 'name': 'Dinheiro na Carteira', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'b71f1c7eb1f142d9ae5e4d67959e1546', 'code': '', 'type': 'CASH', 'description': 'Dinheiro na Carteira', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '3065ea462e92466ba32536a369cafb39'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D700>, 'name': 'Passivo', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '8f14959583c94e0683565b020757a7e0', 'code': '', 'type': 'LIABILITY', 'description': 'Passivo', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '9359f19ba676472f890562ba945a7f55'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D7C0>, 'name': 'Contas a Pagar', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '9359f19ba676472f890562ba945a7f55', 'code': '', 'type': 'LIABILITY', 'description': 'Contas a Pagar', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '96f2696fc9294ab3b85e86ac00c12f96'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D880>, 'name': 'Cartão de Crédito', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '96f2696fc9294ab3b85e86ac00c12f96', 'code': '', 'type': 'CREDIT', 'description': 'Cartão de Crédito', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '867ba91deae74b0bb0d81f6f82eb9db1'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042D940>, 'name': 'Receitas', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '8f14959583c94e0683565b020757a7e0', 'code': '', 'type': 'INCOME', 'description': 'Receitas', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'c0491f004c0540babe144c8917843f5c'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DA00>, 'name': 'Bônus', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c0491f004c0540babe144c8917843f5c', 'code': '', 'type': 'INCOME', 'description': 'Bônus', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '5818c1db9bfd4a85a090c94098377307'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DAC0>, 'name': 'Presentes Recebidos', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c0491f004c0540babe144c8917843f5c', 'code': '', 'type': 'INCOME', 'description': 'Presentes Recebidos', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '506a0a38ad86427e91ccdaffcd0266f4'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DB80>, 'name': 'Juros Recebidos', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c0491f004c0540babe144c8917843f5c', 'code': '', 'type': 'INCOME', 'description': 'Juros Recebidos', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'f38c15721a834089b1ab9db251b1201d'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DBB0>, 'name': 'Juros Conta Corrente', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'f38c15721a834089b1ab9db251b1201d', 'code': '', 'type': 'INCOME', 'description': 'Juros Conta Corrente', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '29413b0bcce74faabde947271b34e02f'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DC10>, 'name': 'Outros Juros', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'f38c15721a834089b1ab9db251b1201d', 'code': '', 'type': 'INCOME', 'description': 'Outros Juros', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '75507d3737fb40cf9730826cfb0fd796'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DC70>, 'name': 'Juros Conta Poupança', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'f38c15721a834089b1ab9db251b1201d', 'code': '', 'type': 'INCOME', 'description': 'Juros Conta Poupança', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'b9c55d08af2c478d8989e68ddc2b0f90'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DCD0>, 'name': 'Outras Receitas', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c0491f004c0540babe144c8917843f5c', 'code': '', 'type': 'INCOME', 'description': 'Outras Receitas', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'b42eaecf5b8e4acdb3da193103e5cebb'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DD30>, 'name': 'Salário', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c0491f004c0540babe144c8917843f5c', 'code': '', 'type': 'INCOME', 'description': 'Salário', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '9e687a99a650481586d958cced47e730'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DD90>, 'name': 'Despesas', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '8f14959583c94e0683565b020757a7e0', 'code': '', 'type': 'EXPENSE', 'description': 'Despesas', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'e4465157fe744bb292247e32032eea71'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DDF0>, 'name': 'Ajustes', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Ajustes', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '7ec19863275b4b938f393dcc5eabab0d'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DE50>, 'name': 'Automóvel', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Automóvel', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '066f9d7400f946669e3e745a4604288e'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DEB0>, 'name': 'Impostos', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '066f9d7400f946669e3e745a4604288e', 'code': '', 'type': 'EXPENSE', 'description': 'Impostos', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'c90b30a9ca3743ca8e6af10c0aace606'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DF10>, 'name': 'IRF', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c90b30a9ca3743ca8e6af10c0aace606', 'code': '', 'type': 'EXPENSE', 'description': 'IRF', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '541186396bfb4f269e3744f3c10c26f6'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF5042DF70>, 'name': 'INSS', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c90b30a9ca3743ca8e6af10c0aace606', 'code': '', 'type': 'EXPENSE', 'description': 'INSS', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'aa6e77e937634696aebcc6a6f04ce533'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457040>, 'name': 'Outros Impostos', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c90b30a9ca3743ca8e6af10c0aace606', 'code': '', 'type': 'EXPENSE', 'description': 'Outros Impostos', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '4e09231790704dc8b53d197737abd681'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457070>, 'name': 'CPMF', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'c90b30a9ca3743ca8e6af10c0aace606', 'code': '', 'type': 'EXPENSE', 'description': 'CPMF', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'f29f2a344f8a47d18fb6cdf713d3ba1f'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504570D0>, 'name': 'Combustível', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '066f9d7400f946669e3e745a4604288e', 'code': '', 'type': 'EXPENSE', 'description': 'Combustível', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '5880710496c24999b16e452b3358e8e8'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457130>, 'name': 'Estacionamento', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '066f9d7400f946669e3e745a4604288e', 'code': '', 'type': 'EXPENSE', 'description': 'Estacionamento', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '691d71fc6ea44986972725230dca9572'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457190>, 'name': 'Reparos e Manutenção', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '066f9d7400f946669e3e745a4604288e', 'code': '', 'type': 'EXPENSE', 'description': 'Reparos e Manutenção', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'daa7fbe4f3f2407aa1fbfe6103edd5d4'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504571F0>, 'name': 'Taxas Bancárias', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Taxas Bancárias', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'e4170802c8494eb68ba3eae72d955c9c'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457250>, 'name': 'Livros', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Livros', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'e9feb30758764920a7abbbf963bb83e0'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504572B0>, 'name': 'Tv por assinatura', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Tv por assinatura', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '2960914245c045d9a19bfc376c31ccf9'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457310>, 'name': 'Doações', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Doações', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '7ea193a2724443f0bf77a7e59afb2bcd'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457370>, 'name': 'Vestuário', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Vestuário', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '158934fd7fb749ab818660f6a656fc67'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504573D0>, 'name': 'Computador', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Computador', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '3787edd8ef6f4ede88c23b946c8ff5a9'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457430>, 'name': 'Refeições Fora', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Refeições Fora', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '86d05ee6b3374d51813477443573dad9'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457490>, 'name': 'Educação', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Educação', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '53c13432927b4ecf9035fa625f2ea7c4'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504574F0>, 'name': 'Diversão', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Diversão', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '6aef09545c6943aa97f0ee4d86701a0e'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457550>, 'name': 'Música/Cinema', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '6aef09545c6943aa97f0ee4d86701a0e', 'code': '', 'type': 'EXPENSE', 'description': 'Música/Cinema', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'efe73d4fa0b0431bb391eaac3e819794'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504575B0>, 'name': 'Passeios', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '6aef09545c6943aa97f0ee4d86701a0e', 'code': '', 'type': 'EXPENSE', 'description': 'Passeios', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '04825749fd1e4fedb0252f01117df7c2'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457610>, 'name': 'Viagens', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '6aef09545c6943aa97f0ee4d86701a0e', 'code': '', 'type': 'EXPENSE', 'description': 'Viagens', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'fef6fde6e70549bab96959795fe3d893'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457670>, 'name': 'Presentes', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Presentes', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'ac12fad162874d06a62a3d73ba59f157'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504576D0>, 'name': 'Mercearia', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Mercearia', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '8d4affedf6b5428c90f018e2ab1b6a22'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457730>, 'name': 'Passatempos', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Passatempos', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '30af3df74cfa436a903bf67cfd264a68'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457790>, 'name': 'Seguro', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Seguro', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '2279d6a749ee4118817c485d91071336'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504577F0>, 'name': 'Seguro Automóvel', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '2279d6a749ee4118817c485d91071336', 'code': '', 'type': 'EXPENSE', 'description': 'Seguro Automóvel', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '08d265786c9a4ded85a10c2cbcb37aa5'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF503F5460>, 'name': 'Seguro Saúde', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '2279d6a749ee4118817c485d91071336', 'code': '', 'type': 'EXPENSE', 'description': 'Seguro Saúde', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '18b08496355742368737042f51506a6d'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457850>, 'name': 'Seguro de Vida', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': '2279d6a749ee4118817c485d91071336', 'code': '', 'type': 'EXPENSE', 'description': 'Seguro de Vida', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '985dadd121a74e0a875172e0c83bb2a1'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF504578B0>, 'name': 'Lavandaria', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Lavandaria', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '4c59424c5d054a54b633ce813327e22c'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457910>, 'name': 'Despesas com Saúde', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Despesas com Saúde', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': 'c8f354c94a8d432d97dbe74dfa0edd58'}
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x000001FF50457970>, 'name': 'Outras', 'commodity_guid': 'de9498f01a7d43fa8e0e3d1d06752a13', 'parent_guid': 'e4465157fe744bb292247e32032eea71', 'code': '', 'type': 'EXPENSE', 'description': 'Outras', '_commodity_scu': 100, 'hidden': 0, '_non_std_scu': 0, '_placeholder': 0, 'guid': '44788967efd341dea5a9639a48e6936b'}

# Trabalho com Arquivos Sqlachemy

In [1]:
from database import engine, init_db, drop_all_tables, Base, db_session
from models.arquivo import Arquivo, StCarga, TpArquivo, popula_tabelas
from models.ofx import Ofx, OfxTransacao
from pprint import pprint

init_db()

db_session.info

q = db_session.query(Arquivo).all()
print("Existem {} arquivos carregados.".format(len(q)))

Conectado com o banco com sucesso
Existem 652 arquivos carregados.

In [2]:
# Seleciona um arquivo não vazio
arquivo = db_session.query(Arquivo).filter(Arquivo.arquivo_blob.isnot(None)).first()
print(arquivo)

< Arquivo(sqarquivo='1', nome='OUROCARD_AMEX_PLATINUM_ESTILO_12_2012-03-25.2.txt', path='arquivos/ofx\cartão\Amex\2012', md5hash='31ecb41613c43566f86ea164c1e28ea5', tscriacao='2021-08-21 00:59:09.382215') >

In [3]:
from models.arquivo import Arquivo
%time a = Arquivo('OUROCARD_ELO_NANQUIM-Dez_20.ofx','arquivos/ofx/cartão/bb')

Wall time: 367 ms

# Trabalho com Ofx

https://stackoverflow.com/questions/192907/xml-parsing-elementtree-vs-sax-and-dom

- xml.dom completo
- xml.dom.minidom da pespectiva de leitura tem tudo
- xml.etree is much easier to use and it requires less memory than XML DOM
- xml.etree.cElementTree c implemetation

In [7]:
lista_arquivos = db_session.query(Arquivo).filter(Arquivo.arquivo_blob.isnot(None)).all()
print("Arquivos encontrados: {}".format(len(lista_arquivos)))

# %time d = Ofx.parser_bytes(lista_arquivos[0].arquivo_blob)
# %time d = Ofx.parser_byte_a_bytes(lista_arquivos[0].arquivo_blob)

Arquivos encontrados: 652

In [8]:
from timeit import default_timer as timer
from datetime import timedelta


cronometro = timer()
print('Teste')
print("Tempo Transcorrido {}".format(timedelta(seconds=timer()-cronometro))); cronometro = timer()

Teste
Tempo Transcorrido 0:00:00.000366

In [14]:
import models.ofx

o = Ofx()
o.tree = Ofx.parser_bytes(lista_arquivos[1].arquivo_blob)

o.tpofx = o.get_tipo()

# conta

# instituicao

# OFX DO BANCO DO BRASIL
o.dhservidor = o.busca_conteudo('datetime','SIGNONMSGSRSV1/SONRS/DTSERVER')
o.dtinicio = o.busca_conteudo('datetime','.//BANKTRANLIST/DTSTART')  
o.dtfim = o.busca_conteudo('datetime','.//BANKTRANLIST/DTEND')

if o.tpofx == 'extrato':
    # conta
    o.tpconta = o.busca_conteudo('texto','.//BANKACCTFROM/ACCTTYPE') #>CHECKING</ACCTTYPE>
    o.cdbanco = o.busca_conteudo('texto','.//BANKACCTFROM/BANKID') #>1</BANKID>
    o.agencia = o.busca_conteudo('texto','.//BANKACCTFROM/BRANCHID') #>5929-3</BRANCHID> #não tem na caixa
    o.conta = o.busca_conteudo('texto','.//BANKACCTFROM/ACCTID') #>94944-2</ACCTID>

    # saldo
    o.dtsaldo = o.busca_conteudo('datetime','.//LEDGERBAL/DTASOF') #>20210810</DTASOF')
    o.vlsaldo = o.busca_conteudo('float','.//LEDGERBAL/BALAMT') #>-19098.70</BALAMT')

elif o.tpofx == 'cartão':
# cartao
    o.bandeira = None
    o.numero_cartão = o.busca_conteudo('texto','.//CCACCTFROM/ACCTID')
    o.dtvencimento = o.busca_conteudo('datetime','.//LEDGERBAL/DTASOF') #>20210810</DTASOF')
    o.vlfatura = o.busca_conteudo('float','.//LEDGERBAL/BALAMT') #>-19098.70</BALAMT')

# verificar balanço total da fatura,
pprint(o.__dict__)

ModuleNotFoundError: No module named 'models'

In [ ]:
regex = re.compile(r'[ \/-]')
regex.sub("", '01\01/20 00')

In [ ]:
print('Testa cargas:')
%time d = Ofx.parser_byte_a_bytes(lista_arquivos[0].arquivo_blob)
%time d = Ofx.parser_bytes(lista_arquivos[0].arquivo_blob)
print('Lê campos:')
%time o.tree = Ofx.parser_bytes(lista_arquivos[4].arquivo_blob)
%time o.busca_conteudo('texto','.//BANKACCTFROM/ACCTTYPE',o.tree)
%time o.busca_conteudo('datetime','.//LEDGERBAL/DTASOF')
%time o.get_tipo(o.tree)
%time o.get_tipo()

In [ ]:
o.tree = Ofx.parser_bytes(lista_arquivos[1].arquivo_blob)
print(o.tpofx)

transacoes = []
for item in o.tree.findall(".//STMTTRN"):
    transacao = {}
    transacao['tptransacao'] = o.busca_conteudo('texto','TRNTYPE',item)
    transacao['dttrasacao'] = o.busca_conteudo('datetime','DTPOSTED',item)
    transacao['vltransacao'] = o.busca_conteudo('float','TRNAMT',item)
    transacao['idtransacao'] = o.busca_conteudo('texto','FITID',item)
    transacao['saldo'] = o.busca_conteudo('float','CHECKNUM',item)
    transacao['memo'] = o.busca_conteudo('texto','MEMO',item)
    transacao['tptransacao'], transacao['estabelecimento'], transacao['parc'], transacao['nparc'], transacao['cidade'], transacao['pais'] = \
        o.get_memo_slice(o.tpofx,transacao['memo'])

    transacoes.append(transacao)

pprint(transacoes)
#ET.dump(o.tree) 
o.tree.findall(".//STMTTRN")

In [ ]:


cartao = Ofx.parser_bytes(lista_arquivos[0].arquivo_blob)
bb = Ofx.parser_bytes(lista_arquivos[4].arquivo_blob)
caixa = Ofx.parser_bytes(lista_arquivos[5].arquivo_blob)

cartao_tags = list(get_all_tags(cartao).keys())
bb_tags = list(get_all_tags(bb).keys())
caixa_tags = list(get_all_tags(caixa).keys())
cartao_tags.sort()
caixa_tags.sort()
caixa_tags.sort()

print()


# for l in lista_arquivos:
#     print(l.nome)

lista = []
for a in lista_arquivos:
    try:
        o = Ofx.parser_bytes(a.arquivo_blob)
     
        campos = list(get_all_tags(o).keys())
        campos.sort()
        lista = set(campos) ^ set(cartao_tags)

        print(tipo_ofx(o))
        
    except:
        print('Erro :' + a.nome)
        
        
        
#print(lista_arquivos[4].arquivo_blob)
# gabarito = set(lista[0].keys())        
# for campos in lista:
#     lista = set(campos.keys()) ^ gabarito
#     print(lista)

#['ACCTID', 'BALAMT', 'BANKTRANLIST', 'CCACCTFROM', 'CCSTMTRS', 'CCSTMTTRNRS', 'CODE', 'CREDITCARDMSGSRSV1', 'CURDEF', 'DTASOF', 'DTEND', 'DTPOSTED', 'DTSERVER', 'DTSTART', 'FI', 'FID', 'FITID', 'LANGUAGE', 'LEDGERBAL', 'MEMO', 'OFX', 'ORG', 'SEVERITY', 'SIGNONMSGSRSV1', 'SONRS', 'STATUS', 'STMTTRN', 'TRNAMT', 'TRNTYPE', 'TRNUID']
#CREDITCARDMSGSRSV1
#BANKMSGSRSV1

#caixa_tags
#{'CCSTMTTRNRS', 'ACCTTYPE', 'CHECKNUM', 'BANKACCTFROM', 'STMTRS', 'FID', 'ORG', 'FI', 'BANKID', 'BANKMSGSRSV1', 'CCACCTFROM', 'CCSTMTRS', 'CREDITCARDMSGSRSV1', 'STMTTRNRS'}
#{'CCSTMTTRNRS', 'STMTRS', 'BANKID', 'CCSTMTRS', 'STMTTRNRS', 'BRANCHID', 'ACCTTYPE', 'CHECKNUM', 'BANKACCTFROM', 'BANKMSGSRSV1', 'REFNUM', 'CCACCTFROM', 'CREDITCARDMSGSRSV1'}

In [ ]:
lista = list(get_all_tags(cartao).keys())
tags = get_all_tags(caixa)

for campo in lista:
    print(campo)
    tags.pop(campo,None)

'''
só cartão tem
{'FI': 1,
 'ORG': 1,
 'FID': 1,
 'CREDITCARDMSGSRSV1': 1,
 'CCSTMTTRNRS': 1,
 'CCSTMTRS': 1,
 'CCACCTFROM': 1}
 
só caixa tem
{' ': 1,
 'STMTTRNRS': 1,
 'STMTRS': 1,
 'BANKACCTFROM': 1,
 'BANKID': 1,
 'ACCTTYPE': 1,
 'CHECKNUM': 2}
'''
tags

In [ ]:
#OFX/SIGNONMSGSRSV1/SONRS/STATUS/CODE 0
#OFX/SIGNONMSGSRSV1/SONRS/STATUS/SEVERITY INFO
OFX/SIGNONMSGSRSV1/SONRS/DTSERVER 20210730095614
#OFX/SIGNONMSGSRSV1/SONRS/LANGUAGE POR
#OFX/SIGNONMSGSRSV1/SONRS/FI/ORG BANCO DO BRASIL
#OFX/SIGNONMSGSRSV1/SONRS/FI/FID 1

#OFX/CREDITCARDMSGSRSV1/CCSTMTTRNRS/TRNUID 1
#OFX/CREDITCARDMSGSRSV1/CCSTMTTRNRS/STATUS/CODE 0
#OFX/CREDITCARDMSGSRSV1/CCSTMTTRNRS/STATUS/SEVERITY INFO
#OFX/CREDITCARDMSGSRSV1/CCSTMTRS/CURDEF BRL
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/CCACCTFROM/ACCTID 6516000000002083
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/LEDGERBAL/BALAMT -19098.70
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/LEDGERBAL/DTASOF 20210810

OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST>

OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/DTSTART>20201212</DTSTART>        
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/DTEND>20210727</DTEND>
    
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/STMTTRN>
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/STMTTRN/TRNTYPE >CREDIT</TRNTYPE>
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/STMTTRN/DTPOSTED >20210712</DTPOSTED>
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/STMTTRN/TRNAMT >29050.20</TRNAMT>
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/STMTTRN/FITID >2021071265160000000020830000000000</FITID>
OFX/CREDITCARDMSGSRSV1/CCSTMTRS/BANKTRANLIST/STMTTRN/MEMO >PGTO DEBITO CONTA 5929 000004004  200211</MEMO>

In [ ]:
import os
from xml.etree import cElementTree as ET  # C implementation of xml.etree.ElementTree
from xml.parsers.expat import ExpatError  # XML formatting errors

In [ ]:
cartao = parser_ofx('OUROCARD_ELO_NANQUIM-Ago_21.ofx')
extrato_bb = parser_ofx('periodo_2021-07-30_parcial.ofx')
extrato_caixa = parser_ofx('caixa/7CS9gkEte6hnsgkMQVc+AgAebb.nodelx188_nbcinter05l-lx188.ofx')

ET.dump(cartao.find('.//CCACCTFROM'))
cartao.find('.//BANKACCTFROM')
ET.dump(extrato_bb.find('.//BANKACCTFROM'))
ET.dump(extrato_caixa.find('.//BANKACCTFROM'))

In [ ]:
arquivos = ['OUROCARD_VISA_INFINITE-Ago_21.ofx','OUROCARD_MASTERCARD_BLACK-Ago_21.ofx','OUROCARD_ELO_NANQUIM-Ago_21.ofx']
#arquivos = ['periodo_2021-07-30_parcial.ofx']
#arquivos = ['caixa/7CS9gkEte6hnsgkMQVc+AgAebb.nodelx188_nbcinter05l-lx188.ofx']

root = parser_ofx(arquivos[0])
print(get_tags_stmttrn(root).keys())
#print(testa_stmttrn(root))

#print(ET.tostring(root))
#print(ET.dump(root.find(".//STMTTRN")))
#print(ET.dump(root))
#for item in root.findall(".//"):
#    print(ET.dump(item))

In [ ]:
arquivos = ['OUROCARD_VISA_INFINITE-Ago_21.ofx','OUROCARD_MASTERCARD_BLACK-Ago_21.ofx','OUROCARD_ELO_NANQUIM-Ago_21.ofx']
arquivos = ['caixa/7CS9gkEte6hnsgkMQVc+AgAebb.nodelx188_nbcinter05l-lx188.ofx']
arquivos = ['periodo_2021-07-30_parcial.ofx']

transacoes = []
for nome_arquivo in arquivos:
    root = parser_ofx(nome_arquivo)
    print(testa_stmttrn(root))
    print(get_tags_stmttrn(root))
    #transacoes = transacoes + get_stmttrn(root)
    
    
#df = pd.DataFrame(transacoes)
#df.groupby(['estabelecimento']).size()

# Teste de Python e Gnucash

In [ ]:
with open_book(path_gnucash, readonly=False, open_if_lock=True) as book:
    root_acct = book.root_account
    print(root_acct)
    
    # A commoditie já existe
    #brl = create_currency_from_ISO("BRL")
    
    '''expenses_acct = Account(
        parent=root_acct, name="Expenses", type="EXPENSE", commodity=brl
    )'''
    '''savings_acct = Account(
        parent=root_acct, name="Savings", type="BANK", commodity=brl
    )'''
    '''opening_acct = Account(
        parent=root_acct, name="Opening Balance", type="EQUITY", commodity=brl
    )'''
    num1 = Decimal("4")
    num2 = Decimal("100")
    num3 = Decimal("15")

    # create transaction with core objects in one step
    trans1 = Transaction(
        currency=brl,
        description="Groceries",
        splits=[
            Split(value=num1, account=expenses_acct),
            Split(value=-num1, account=savings_acct),
        ],
    )

    # create transaction with core object in multiple steps
    trans2 = Transaction(currency=brl, description="Opening Savings Balance")

    split3 = Split(value=num2, account=savings_acct, transaction=trans2)

    split4 = Split(value=-num2, account=opening_acct, transaction=trans2)

    # create transaction with factory function
    from piecash.core.factories import single_transaction

    trans3 = single_transaction(
        None, None, "Pharmacy", num3, savings_acct, expenses_acct
    )

    book.save()

In [ ]:
from piecash import open_book, ledger, Split

# open a book
with open_book(path_gnucash, readonly=True, open_if_lock=True
) as mybook:
    # iterate on all the transactions in the book
    for transaction in mybook.transactions:
        print(transaction)
        print(transaction.description)
        # add some extra text to the transaction description
        transaction.description = (
            transaction.description + " (some extra info added to the description)"
        )
        # iterate over all the splits of the transaction
        # as we will modify the transaction splits in the loop,
        # we need to use list(...) to take a copy of the splits at the start of the loop
        for split in list(transaction.splits):
            # create the new split (here a copy of the each existing split
            # in the transaction with value/quantity divided by 10)
            new_split = Split(
                account=split.account,
                value=split.value / 10,
                quantity=split.quantity / 10,
                memo="my new split",
                transaction=transaction,  # attach the split to the current transaction
            )
    # register the changes (but not save)
    mybook.flush()

    # print the book in ledger format to view the changes
    print(ledger(mybook))

    # save the book
    # this will raise an error as readonly=True (change to readonly=False to successfully save the book)
    mybook.save()

#

In [ ]:
# trabalha com transação

from piecash import open_book, ledger, Split

# open a book
with open_book(path_gnucash, readonly=True, open_if_lock=True
) as mybook:
    # iterate on all the transactions in the book
    for transaction in mybook.transactions:
        print(transaction.description)
        print(transaction.__dict__)
        
        # iterate over all the splits of the transaction
        # as we will modify the transaction splits in the loop,
        # we need to use list(...) to take a copy of the splits at the start of the loop
        for split in list(transaction.splits):
            # create the new split (here a copy of the each existing split
            # in the transaction with value/quantity divided by 10)
            
            print(split)

In [ ]:
from __future__ import print_function
from piecash import create_book

# create by default an in memory sqlite version
with create_book(echo=False) as book:

    print("Book is saved:", book.is_saved, end=" ")
    print(" ==> book description:", book.root_account.description)

    print("changing description...")
    book.root_account.description = "hello, book"
    print("Book is saved:", book.is_saved, end=" ")
    print(" ==> book description:", book.root_account.description)

    print("saving...")
    book.save()

    print("Book is saved:", book.is_saved, end=" ")
    print(" ==> book description:", book.root_account.description)

    print("changing description...")
    book.root_account.description = "nevermind, book"
    print("Book is saved:", book.is_saved, end=" ")
    print(" ==> book description:", book.root_account.description)

    print("cancel...")
    book.cancel()

    print("Book is saved:", book.is_saved, end=" ")
    print(" ==> book description:", book.root_account.description)